openapi: 3.0.0
info:
  title: Movie Quotes API
  description: Movie quotes
  version: 0.1.9

servers:
  - url: http://localhost:3001/
    description: local server
  - url: https://moviequotes-api.nina.redberryinternship.ge/
    description: production server

    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  /signup:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
              example:
                username: nyx123
                email: nyx@gmail.com
                password: nyx12345678
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User Created Successfully

  /login:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user: 
                  type: string
                password: 
                  type: string
                remember: 
                  type: boolean
              required:
                  - user
                  - password
              example:
                user: nyx123
                password: nyx12345678
                remember: true
      responses:
        '200':
          description: Logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                 token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmViYWM2ZGM5NjQzMGU4YzgzMTgz



                
                    
  /verify-account:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
              example:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Your account is verified
  
  /auth-google:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                   type: string
              required:
                - username
                - email
              example:
                username: ketokote
                email: kote@keto.ge
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User Created and verified Successfully
  
  
  /password-recovery:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                   type: string
              required:
                - email
              example:
                email: ninadarbaidze66@gmail.com
      responses:
        '200':
          description: Link is sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password recovery link is sent
  
  /update-password:
    post:
        tags:
          - Authentication
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
                  token:  
                    type: string
                required:
                    - password
                    - token
                example:
                      password: ninadarbaidze66@gmail.com
                      token: dsdsndajsdjadhsjhdsjdhsjhdsbbbcbbcc343
                      
        responses:
          '200':
            description: Password updated
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Password is updated

  /update-profile:
    post: 
      tags:
        - Profile
      security:
        - bearerAuth: []
      requestBody:
            content:
                 multipart/form-data:
                  schema:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
                      password:
                        type: string
                      userId:
                        type: string
                      image:
                        type: string
                        format: binary
                        required:
                          - userId
                        example:
                          usename: nyx123
                          email: nyx@gmail.com
                          password: nyx@gmail.com
                          userId: ikjge89087nnvr6
                          image: filename
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Profile updated successfully


  /profile/{id}:
   get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
          description: user id
      tags:
        - Profile
      security:
        - bearerAuth: []
      responses:
        '200': 
          description: Return user info
          content:
            application/json:
              schema: 
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      username: 
                        type: string
                      email: 
                        type: string
                      profileImage: 
                        type: string
              example:
                user:
                    _id: 62b9cf91d2ee7fff6bf3b7cb
                    username: nyx
                    email: nyx@gmail.com
                    profileImage: images/profile-image.png



  /movies:
    get: 
      tags:
        - Movies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Movie list
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    en:
                      type: object
                      properties:
                          movieName: 
                              type: string
                              example: Fight Club
                          director: 
                              example: David Fincher
                          description: 
                              type: string
                              example: Unhappy with his capitalistic lifestyle, a white-collared insomniac forms an underground fight club with Tyler, a careless soap salesman. Soon, their venture spirals down into something sinister.    
                    ge:
                      type: object
                      properties:
                        movieName: 
                            type: string
                            example: მებრძოლთა კლუბი
                        director: 
                            type: string
                            example: დევიდ ფინჩერი
                        description: 
                            type: string
                            example: ფილმის განმარტება
                    _id: 
                      type: string
                      example: djsjdskjdjk32ids99nnjsdl20023
                    image: 
                      type: string
                      example: images/movie-image.png
                    budget: 
                        type: number
                        example: 100000000
                    userId:
                      type: object
                      properties:
                        username: 
                            type: string
                            example: nyx
                        email: 
                            type: string
                            example: nyx@gmail.com
                        password: 
                            type: string
                            example: 'nyx123'
                        verified: 
                            type: boolean
                            example: true
                        profileImage: 
                            type: string
                            example: images/profile-image.png
                        genres: 
                            type: array
                            example: ["genres:Horror, Genres:Thriller"]
                        movies: 
                          type: array
                          items: 
                              type: string
                              example: jsdskdskdjskjdskjdsk4343fd

                                   



